import { ATLANTA_PEAK_SUN_HOURS, SOLAR_PERFORMANCE_RATIO, DAYLIGHT_HOURS } from './constants'

// Hourly solar output factors (0–1) for each hour of the day given a month.
// Uses a sin curve centered on solar noon between sunrise and sunset.
function hourlyFactors(month: number): number[] {
  const [sunrise, sunset] = DAYLIGHT_HOURS[month]
  const factors = new Array(24).fill(0)
  let total = 0
  for (let h = sunrise; h < sunset; h++) {
    // Mid-point of hour for the sin curve
    const t = (h + 0.5 - sunrise) / (sunset - sunrise)
    const f = Math.sin(Math.PI * t)
    factors[h] = f
    total += f
  }
  if (total > 0) {
    for (let h = sunrise; h < sunset; h++) {
      factors[h] /= total
    }
  }
  return factors
}

// Cache factors by month to avoid recomputing per-hour
const factorCache: Record<number, number[]> = {}
function getFactors(month: number): number[] {
  if (!factorCache[month]) factorCache[month] = hourlyFactors(month)
  return factorCache[month]
}

// kWh generated by systemKW system during `hour` (0–23) in `month` (1–12)
export function solarOutputKWh(systemKW: number, month: number, hour: number): number {
  const dailyGen = systemKW * ATLANTA_PEAK_SUN_HOURS[month] * SOLAR_PERFORMANCE_RATIO
  return dailyGen * getFactors(month)[hour]
}
