// Natural gas provider rates — approximate as of January 2025
// Sources: provider websites, state public service commission filings
// DISCLAIMER: Rates change frequently. Always verify current rates with your provider.

import type { GasStateDef } from './types'

// Months considered "heating season" for color coding (Nov–Mar)
export const HEATING_MONTHS = new Set([11, 12, 1, 2, 3])

export const GAS_STATES: Record<string, GasStateDef> = {
  ga: {
    id: 'ga',
    name: 'Georgia',
    isDeregulated: true,
    // AGL (Atlanta Gas Light) delivers gas to all Georgia customers regardless of marketer.
    // These distribution charges are added to every plan's cost.
    distributionRatePerTherm: 0.254,
    distributionMonthlyFee: 9.15,
    distributionLabel: 'Atlanta Gas Light (AGL) distribution',
    rateDate: 'January 2025',
    rateSource: 'Georgia Public Service Commission / provider websites',
    csvFormat: 'Two columns: Month (e.g. "January 2025" or "2025-01") and Therms',
    uploadInstructions: [
      'Log in to your gas marketer\'s website (GNG, Gas South, Scana, etc.)',
      'Navigate to Billing History or My Account → Usage',
      'Export or download monthly usage as CSV or Excel',
      'Alternatively, enter each month\'s therms manually below',
      'Tip: Check your paper or PDF bill — therms used is listed near the top',
    ],
    plans: [
      // ── Georgia Natural Gas (GNG) ──────────────────────────────────────
      {
        id: 'gng_myvalue12',
        name: 'GNG MyValue 12-Month',
        shortName: 'GNG MyValue 12',
        provider: 'Georgia Natural Gas',
        description: '12-month fixed rate. Most popular plan, no enrollment fee.',
        ratePerTherm: 0.589,
        monthlyFee: 9.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Commodity rate fixed for 12 months — won\'t fluctuate with market.',
          'Early termination fee may apply.',
        ],
      },
      {
        id: 'gng_budget12',
        name: 'GNG Budget Smart 12-Month',
        shortName: 'GNG Budget Smart',
        provider: 'Georgia Natural Gas',
        description: 'Lower per-therm rate, higher monthly fee. Best for heavy gas users.',
        ratePerTherm: 0.529,
        monthlyFee: 14.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Lower commodity rate but $5/mo higher service fee than MyValue.',
          'Breaks even vs MyValue at ~83 therms/month — better for heavier users.',
        ],
      },
      {
        id: 'gng_secure24',
        name: 'GNG Secure Fixed 24-Month',
        shortName: 'GNG Secure 24',
        provider: 'Georgia Natural Gas',
        description: '24-month price lock for maximum long-term stability.',
        ratePerTherm: 0.619,
        monthlyFee: 9.95,
        isVariable: false,
        contractMonths: 24,
        notes: [
          'Slightly higher rate in exchange for two-year price certainty.',
          'Protects against market price spikes for 24 months.',
        ],
      },
      {
        id: 'gng_variable',
        name: 'GNG Month-to-Month',
        shortName: 'GNG Variable',
        provider: 'Georgia Natural Gas',
        description: 'No contract. Rate adjusts each month with market conditions.',
        ratePerTherm: 0.749,
        monthlyFee: 9.95,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Rate shown is a 12-month average estimate — actual rate varies monthly.',
          'No early termination fee. Can switch providers at any time.',
          'Historically higher than fixed rates; beneficial only when market dips.',
        ],
      },
      // ── Gas South ─────────────────────────────────────────────────────
      {
        id: 'gassouth_12',
        name: 'Gas South 12-Month Fixed',
        shortName: 'Gas South 12',
        provider: 'Gas South',
        description: '12-month fixed rate with a lower monthly service fee.',
        ratePerTherm: 0.549,
        monthlyFee: 6.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Competitive fixed rate with lowest monthly fee among Gas South plans.',
        ],
      },
      {
        id: 'gassouth_24',
        name: 'Gas South 24-Month Fixed',
        shortName: 'Gas South 24',
        provider: 'Gas South',
        description: '24-month fixed rate for longer price protection.',
        ratePerTherm: 0.569,
        monthlyFee: 6.95,
        isVariable: false,
        contractMonths: 24,
        notes: [
          'Slightly higher rate than 12-month for an extra year of price lock.',
        ],
      },
      {
        id: 'gassouth_budget',
        name: 'Gas South Budget Buster 12-Month',
        shortName: 'Gas South Budget',
        provider: 'Gas South',
        description: 'Lowest per-therm rate, highest monthly fee. Built for high-usage homes.',
        ratePerTherm: 0.489,
        monthlyFee: 19.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Lowest commodity rate on the market, but $13/mo higher fee than 12-Month Fixed.',
          'Breaks even vs Gas South 12-Month at ~217 therms/month — best for very high users.',
        ],
      },
      {
        id: 'gassouth_variable',
        name: 'Gas South Month-to-Month',
        shortName: 'Gas South Variable',
        provider: 'Gas South',
        description: 'No contract. Rate adjusts monthly. Maximum flexibility.',
        ratePerTherm: 0.699,
        monthlyFee: 6.95,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Rate shown is a 12-month average estimate — actual rate varies monthly.',
          'No cancellation fee. Good for short-term or uncertain housing situations.',
        ],
      },
      // ── Scana Energy ──────────────────────────────────────────────────
      {
        id: 'scana_12',
        name: 'Scana PriceGuard 12-Month',
        shortName: 'Scana 12',
        provider: 'Scana Energy',
        description: '12-month fixed rate with price protection guarantee.',
        ratePerTherm: 0.569,
        monthlyFee: 8.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Competitive fixed rate. No enrollment fee for residential customers.',
        ],
      },
      // ── True Natural Gas ──────────────────────────────────────────────
      {
        id: 'true_12',
        name: 'True Natural Gas 12-Month',
        shortName: 'True NG 12',
        provider: 'True Natural Gas',
        description: 'Competitive 12-month fixed rate from an independent marketer.',
        ratePerTherm: 0.539,
        monthlyFee: 7.95,
        isVariable: false,
        contractMonths: 12,
        notes: [
          'Smaller marketer with competitive rates and low monthly fee.',
        ],
      },
    ],
  },

  fl: {
    id: 'fl',
    name: 'Florida',
    isDeregulated: false,
    // Florida has a regulated gas market — utilities provide both delivery and commodity.
    // Distribution is bundled into the plan rate; set to 0 to avoid double-counting.
    distributionRatePerTherm: 0,
    distributionMonthlyFee: 0,
    distributionLabel: 'Distribution included in rate (regulated utility)',
    rateDate: 'January 2025',
    rateSource: 'Florida Public Service Commission / utility rate schedules',
    csvFormat: 'Two columns: Month (e.g. "January 2025" or "2025-01") and Therms',
    uploadInstructions: [
      'Log in to your utility\'s website (Peoples Gas, Florida City Gas, etc.)',
      'Navigate to My Account → Billing History',
      'Download usage data as CSV if available',
      'Or enter each month\'s therms manually below',
      'Therms used appears on your monthly bill statement',
    ],
    plans: [
      {
        id: 'fl_peoplesgas',
        name: 'Peoples Gas Standard Residential',
        shortName: 'Peoples Gas',
        provider: 'Peoples Gas',
        description: 'Standard regulated rate for Peoples Gas service territory (Tampa area and most of FL).',
        ratePerTherm: 0.629,
        monthlyFee: 13.50,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by Florida PSC — no choice of marketer.',
          'Rate shown is approximate and subject to PSC-approved adjustments.',
        ],
      },
      {
        id: 'fl_floridacitygas',
        name: 'Florida City Gas Standard Residential',
        shortName: 'Florida City Gas',
        provider: 'Florida City Gas',
        description: 'Standard regulated rate for Florida City Gas territory (South Florida).',
        ratePerTherm: 0.648,
        monthlyFee: 14.00,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by Florida PSC. Rate shown is approximate.',
          'Contact Florida City Gas directly for current rates.',
        ],
      },
      {
        id: 'fl_teco',
        name: 'TECO Peoples Gas (Reduced Income)',
        shortName: 'Peoples Gas Reduced',
        provider: 'Peoples Gas',
        description: 'Reduced income assistance rate for qualifying low-income households.',
        ratePerTherm: 0.559,
        monthlyFee: 7.50,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Income-based assistance program. Must apply and qualify with Peoples Gas.',
          'Rate shown is approximate. Visit peoplesgas.com for eligibility details.',
        ],
        promoNote: 'Income-based discount program — may qualify for lower rates',
      },
    ],
  },

  tn: {
    id: 'tn',
    name: 'Tennessee',
    isDeregulated: false,
    distributionRatePerTherm: 0,
    distributionMonthlyFee: 0,
    distributionLabel: 'Distribution included in rate (regulated utility)',
    rateDate: 'January 2025',
    rateSource: 'Tennessee Regulatory Authority / utility rate schedules',
    csvFormat: 'Two columns: Month (e.g. "January 2025" or "2025-01") and Therms',
    uploadInstructions: [
      'Log in to your utility\'s website (Piedmont Natural Gas, Nashville Gas, etc.)',
      'Navigate to My Account → Billing or Usage History',
      'Download or export monthly usage data',
      'Or enter each month\'s therms manually below',
    ],
    plans: [
      {
        id: 'tn_piedmont',
        name: 'Piedmont Natural Gas Standard',
        shortName: 'Piedmont',
        provider: 'Piedmont Natural Gas',
        description: 'Standard regulated residential service for Piedmont\'s Tennessee territory.',
        ratePerTherm: 0.598,
        monthlyFee: 15.00,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by Tennessee Regulatory Authority.',
          'Rate shown is approximate. See piedmontng.com for current rates.',
        ],
      },
      {
        id: 'tn_nashvillegas',
        name: 'Nashville Gas Standard',
        shortName: 'Nashville Gas',
        provider: 'Nashville Gas (Atmos)',
        description: 'Standard regulated residential service for Nashville metro area.',
        ratePerTherm: 0.619,
        monthlyFee: 14.50,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate — set by Tennessee Regulatory Authority.',
          'Rate shown is approximate and subject to change.',
        ],
      },
      {
        id: 'tn_piedmont_lifeline',
        name: 'Piedmont Lifeline (Low Income)',
        shortName: 'Piedmont Lifeline',
        provider: 'Piedmont Natural Gas',
        description: 'Reduced rate for income-qualifying households in Piedmont service territory.',
        ratePerTherm: 0.538,
        monthlyFee: 10.00,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Must qualify based on income. Apply at piedmontng.com.',
        ],
        promoNote: 'Income-based discount — check if you qualify',
      },
    ],
  },

  nc: {
    id: 'nc',
    name: 'North Carolina',
    isDeregulated: false,
    distributionRatePerTherm: 0,
    distributionMonthlyFee: 0,
    distributionLabel: 'Distribution included in rate (regulated utility)',
    rateDate: 'January 2025',
    rateSource: 'North Carolina Utilities Commission / utility rate schedules',
    csvFormat: 'Two columns: Month (e.g. "January 2025" or "2025-01") and Therms',
    uploadInstructions: [
      'Log in to your utility\'s website (Piedmont Natural Gas, Dominion Energy, etc.)',
      'Navigate to My Account → Bill History or Usage',
      'Export monthly usage data as CSV if available',
      'Or enter each month\'s therms manually below',
    ],
    plans: [
      {
        id: 'nc_piedmont',
        name: 'Piedmont Natural Gas Standard',
        shortName: 'Piedmont NC',
        provider: 'Piedmont Natural Gas',
        description: 'Standard regulated residential rate for NC Piedmont service territory.',
        ratePerTherm: 0.584,
        monthlyFee: 15.65,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by NC Utilities Commission. Rate shown is approximate.',
        ],
      },
      {
        id: 'nc_dominion',
        name: 'Dominion Energy Standard',
        shortName: 'Dominion NC',
        provider: 'Dominion Energy',
        description: 'Standard regulated residential rate for Dominion Energy NC territory.',
        ratePerTherm: 0.572,
        monthlyFee: 14.50,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by NC Utilities Commission. See dominionenergy.com for current rates.',
        ],
      },
      {
        id: 'nc_piedmont_ecl',
        name: 'Piedmont EqualPay (Budget Billing)',
        shortName: 'Piedmont EqualPay',
        provider: 'Piedmont Natural Gas',
        description: 'Budget billing — same payment every month regardless of seasonal usage.',
        ratePerTherm: 0.584,
        monthlyFee: 15.65,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Same commodity rate as Standard, but billed in equal monthly installments.',
          'Eliminates winter bill spikes — you pay the same amount year-round.',
          'Reconciled annually; you may owe or receive a credit.',
        ],
        promoNote: 'Budget billing — no seasonal spikes',
      },
    ],
  },

  sc: {
    id: 'sc',
    name: 'South Carolina',
    isDeregulated: false,
    distributionRatePerTherm: 0,
    distributionMonthlyFee: 0,
    distributionLabel: 'Distribution included in rate (regulated utility)',
    rateDate: 'January 2025',
    rateSource: 'South Carolina Office of Regulatory Staff / utility rate schedules',
    csvFormat: 'Two columns: Month (e.g. "January 2025" or "2025-01") and Therms',
    uploadInstructions: [
      'Log in to your utility\'s website (Dominion Energy SC, Piedmont, etc.)',
      'Navigate to My Account → Billing or Usage History',
      'Export monthly usage data',
      'Or enter each month\'s therms manually below',
    ],
    plans: [
      {
        id: 'sc_dominion',
        name: 'Dominion Energy Standard Residential',
        shortName: 'Dominion SC',
        provider: 'Dominion Energy',
        description: 'Standard regulated residential gas service for Dominion Energy SC territory.',
        ratePerTherm: 0.591,
        monthlyFee: 14.00,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate set by SC Office of Regulatory Staff.',
          'Rate shown is approximate. Visit dominionenergy.com/south-carolina for current rates.',
        ],
      },
      {
        id: 'sc_piedmont',
        name: 'Piedmont Natural Gas Standard',
        shortName: 'Piedmont SC',
        provider: 'Piedmont Natural Gas',
        description: 'Standard regulated residential service for Piedmont SC territory.',
        ratePerTherm: 0.577,
        monthlyFee: 15.20,
        isVariable: true,
        contractMonths: 0,
        notes: [
          'Regulated rate. See piedmontng.com for current rates.',
        ],
      },
    ],
  },
}

export const GAS_STATE_LIST = Object.values(GAS_STATES).map((s) => ({ id: s.id, name: s.name }))
